{
  "type": "sh.keptn.event.configuration.change",
  "contenttype": "application/json",
  "specversion": "0.2",
  "source": "test-event",
  "data": {
    "project": "dev",
    "stage": "dev",
    "service": "myservice",
    "valuesCanary": {
      "image": "docker.io/keptnexamples/carts:0.10.1"
    },
    "labels": {
      "buildnr": "build17",
      "runby": "JohnDoe"
    }
  }
}
